/**
 * מאגר התרגילים.
 *
 * כל תרגיל מתאר את עצמו במונחים שהמנוע יודע לסנן לפיהם:
 *  - eq:      אפשרויות ציוד. כל איבר הוא *סט* של פריטים שכולם חייבים להתקיים.
 *             די באפשרות אחת שמתקיימת כדי שהתרגיל יהיה זמין בסטודיו.
 *  - stress:  עומס על מפרק/מבנה בסולם 0-3. משמש לסינון לפי פציעות.
 *  - flags:   מאפייני תנועה בינאריים (מעל הראש, כפיפת עמוד שדרה, קפיצה...).
 *             חוקי הפציעות מדברים בשפת הדגלים האלה.
 *  - skill:   1 (כל אחד) עד 5 (דורש שליטה מוטורית גבוהה ולמידה).
 *  - fatigue: עלות עייפות מערכתית — מגביל כמה כאלה ייכנסו לאותו יום.
 */

import { DESCRIPTIONS } from './descriptions.js';

/** מפתחות מפרק/מבנה שעליהם מודדים עומס. */
export const STRESS_KEYS = [
  'lumbar', 'knee', 'shoulder', 'elbow', 'wrist', 'hip', 'neck', 'ankle', 'cardio',
];

/** דגלי תנועה אפשריים. */
export const FLAGS = [
  'overhead',            // הזרוע עוברת מעל גובה הראש
  'spinal_flexion',      // כפיפת עמוד שדרה בעומס
  'spinal_loading',      // עומס צירי על עמוד השדרה
  'spinal_rotation',
  'deep_knee_flexion',   // כפיפת ברך עמוקה (מעבר ל-100°)
  'deep_hip_flexion',
  'end_range_shoulder_ext', // מתיחת חזה/כתף בקצה טווח (פרפר, מקבילים)
  'impact',              // קפיצה / נחיתה
  'high_valsalva',       // עצירת נשימה ולחץ תוך-בטני גבוה
  'grip_intensive',      // דורש אחיזה חזקה
  'floor_transition',    // ירידה ועלייה מהרצפה
  'lying_supine',        // שכיבה על הגב
  'lying_prone',         // שכיבה על הבטן
  'unstable',            // משטח/כלי לא יציב
  'balance',             // דורש שיווי משקל על רגל
  'wrist_extension_load',// עומס על שורש כף היד ביישור
  'axial_neck_load',
  'ballistic',           // תנועה מהירה/מתפרצת
  'head_below_heart',    // הראש מתחת לגובה הלב
  'rapid_position_change', // שינוי תנוחה מהיר (עמידה↔רצפה, קפיצה)
  'hip_adduction_load',  // קירוב ירך בעומס
  'weight_over_head_free', // משקל חופשי מעל הראש/הפנים
  'end_range_joint',     // עבודה בקצה טווח מפרקי
];

const F = (...xs) => xs;

/**
 * חישוב דרישת התרגיל מתוך המאפיינים שכבר תיארנו אותו בהם:
 * כמה עייפות הוא מייצר, האם אפשר להעמיס עליו, והאם הוא גרסה מוקלת.
 */
function computeDemand(d) {
  const type = d.type || 'compound';
  if (type === 'mobility') return 1;
  let n = { low: 1, moderate: 2, high: 3, very_high: 4 }[d.fatigue || 'moderate'];
  if (d.loadable !== false) n += 1;
  if (type === 'compound') n += 1;
  if ((d.tags || []).includes('regression')) n -= 1;
  return Math.max(1, Math.min(5, n));
}

/** רצפת הדרישה לתרגיל עיקרי, לפי רמת המתאמן. */
export const LEVEL_DEMAND_FLOOR = { beginner: 1, novice: 1, intermediate: 2, advanced: 3 };

/**
 * @param {object} d
 */
/** ציוד שאינו נושא משקל מדיד — נוכחותו לבדה אינה הופכת תרגיל למועמס. */
const UNLOADED_EQUIPMENT = new Set([
  'bodyweight', 'mat', 'chair', 'wall', 'stable_support', 'parallel_bars',
  'resistance_band', 'mini_band', 'trx', 'suspension_anchor', 'foam_roller',
  'pilates_mat', 'pilates_ring', 'jump_rope', 'bosu', 'stability_ball',
]);

function ex(d) {
  return {
    id: d.id,
    name: d.name,
    nameEn: d.nameEn,
    /** תיאור מדויק שמוצג למאמן מתחת לשם התרגיל. */
    description: d.description || DESCRIPTIONS[d.id] || '',
    /** תרגיל שנכתב על ידי מאמן ולא מגיע מהמאגר. */
    custom: !!d.custom,
    /**
     * דרישה (1-5): כמה גירוי אימון התרגיל מסוגל לספק.
     * זה מה שמונע מלתת "שכיבות סמיכה לקיר" למתאמן מתקדם רק כי הן בטוחות.
     * מחושב אוטומטית, וניתן לעקוף במפורש בתרגילים חריגים.
     */
    demand: d.demand ?? computeDemand(d),
    type: d.type || 'compound',           // compound | isolation | carry | conditioning | mobility
    pattern: d.pattern,
    primary: d.primary,
    secondary: d.secondary || [],
    eq: d.eq,
    plane: d.plane || 'sagittal',
    unilateral: !!d.unilateral,
    skill: d.skill ?? 2,
    fatigue: d.fatigue || 'moderate',     // low | moderate | high | very_high
    stress: { lumbar: 0, knee: 0, shoulder: 0, elbow: 0, wrist: 0, hip: 0, neck: 0, ankle: 0, cardio: 0, ...(d.stress || {}) },
    flags: d.flags || [],
    setupSeconds: d.setupSeconds ?? 30,
    /** מקום נדרש: small (עמדה) | medium (מזרן/צעד) | large (מסלול הליכה) */
    space: d.space || 'small',
    /** גובה תקרה מינימלי בס"מ; 0 = אין דרישה. */
    ceilingCm: d.ceilingCm ?? 0,
    /** תרגיל רועש (הטחה, קפיצה, הנחת משקל) — רלוונטי לסטודיו בבניין מגורים. */
    noisy: !!d.noisy,
    // טווחי חזרות שהתרגיל "אוהב" — מגביל אבסורדים כמו דדליפט לסט של 30
    repMin: d.repMin ?? 5,
    repMax: d.repMax ?? 20,
    /*
     * האם ניתן להעמיס משקל מדיד (לצורך פרוגרסיה).
     *
     * ברירת המחדל נגזרת מהציוד ולא מהצהרה: תרגיל שכל אפשרויות הציוד שלו
     * הן משקל גוף, מזרן, גומייה או כיסא אינו ניתן להעמסה — הכיסא הוא היעד
     * ולא ההתנגדות. סימון ידני עדיין גובר, למקרים כמו מתח בתוספת משקל.
     */
    loadable: d.loadable ?? (d.eq || []).some((set) => set.some((i) => !UNLOADED_EQUIPMENT.has(i))),
    tags: d.tags || [],
    cues: d.cues || [],
  };
}

export const EXERCISES = [
  // ---------------------------------------------------------------- דחיפה אופקית
  ex({ id: 'bb_bench_press', name: 'לחיצת חזה במוט', nameEn: 'Barbell Bench Press',
    pattern: 'horizontal_push', primary: ['chest'], secondary: ['triceps', 'delts_front'],
    eq: [['barbell', 'bench_flat'], ['barbell', 'bench_flat', 'power_rack']],
    skill: 3, fatigue: 'high', repMin: 3, repMax: 15,
    stress: { shoulder: 2, elbow: 2, wrist: 2 }, flags: F('end_range_shoulder_ext', 'lying_supine', 'high_valsalva'),
    cues: ['שכמות מכונסות', 'מרפקים ב-45 מעלות', 'מוט לקו הפטמה'] }),
  ex({ id: 'db_bench_press', name: 'לחיצת חזה בשיפוע 0 עם משקולות', nameEn: 'Dumbbell Bench Press',
    pattern: 'horizontal_push', primary: ['chest'], secondary: ['triceps', 'delts_front'],
    eq: [['dumbbell', 'bench_flat']], skill: 2, fatigue: 'high', repMin: 5, repMax: 20,
    stress: { shoulder: 2, elbow: 1, wrist: 1 }, flags: F('end_range_shoulder_ext', 'lying_supine') }),
  ex({ id: 'db_incline_press', name: 'לחיצת חזה בשיפוע עליון', nameEn: 'Incline Dumbbell Press',
    pattern: 'horizontal_push', primary: ['chest', 'delts_front'], secondary: ['triceps'],
    eq: [['dumbbell', 'bench_incline']], skill: 2, fatigue: 'high', repMin: 6, repMax: 20,
    stress: { shoulder: 2, elbow: 1 }, flags: F('end_range_shoulder_ext', 'lying_supine') }),
  ex({ id: 'machine_chest_press', name: 'לחיצת חזה במכונה', nameEn: 'Machine Chest Press',
    pattern: 'horizontal_push', primary: ['chest'], secondary: ['triceps', 'delts_front'],
    eq: [['chest_press_machine']], skill: 1, fatigue: 'moderate', repMin: 6, repMax: 25,
    stress: { shoulder: 1, elbow: 1 }, setupSeconds: 20, tags: ['beginner_friendly', 'joint_friendly'] }),
  ex({ id: 'smith_bench_press', name: 'לחיצת חזה בסמית', nameEn: 'Smith Machine Bench Press',
    pattern: 'horizontal_push', primary: ['chest'], secondary: ['triceps'],
    eq: [['smith_machine', 'bench_flat']], skill: 1, fatigue: 'high', repMin: 5, repMax: 20,
    stress: { shoulder: 2, elbow: 1 }, flags: F('lying_supine') }),
  ex({ id: 'pushup', name: 'שכיבות סמיכה', nameEn: 'Push-up',
    pattern: 'horizontal_push', primary: ['chest'], secondary: ['triceps', 'core_anterior', 'delts_front'],
    eq: [['bodyweight']], skill: 2, fatigue: 'moderate', repMin: 5, repMax: 30, loadable: false,
    stress: { shoulder: 1, wrist: 2, elbow: 1 }, flags: F('wrist_extension_load', 'floor_transition'),
    tags: ['no_equipment'] }),
  ex({ id: 'incline_pushup', name: 'שכיבות סמיכה בשיפוע (ידיים גבוה)', nameEn: 'Incline Push-up',
    pattern: 'horizontal_push', primary: ['chest'], secondary: ['triceps'],
    eq: [['bench_flat'], ['step'], ['smith_machine']], skill: 1, fatigue: 'low', repMin: 8, repMax: 30, loadable: false,
    stress: { shoulder: 1, wrist: 1 }, tags: ['regression', 'beginner_friendly'] }),
  ex({ id: 'cable_chest_press', name: 'לחיצת חזה בכבלים בעמידה', nameEn: 'Standing Cable Press',
    pattern: 'horizontal_push', primary: ['chest'], secondary: ['triceps', 'core_anterior'],
    eq: [['cable_crossover']], skill: 2, fatigue: 'moderate', repMin: 8, repMax: 20,
    stress: { shoulder: 1 }, tags: ['standing', 'shoulder_friendly'] }),
  ex({ id: 'floor_press_db', name: 'לחיצת חזה מהרצפה עם משקולות', nameEn: 'Dumbbell Floor Press',
    pattern: 'horizontal_push', primary: ['chest'], secondary: ['triceps'],
    eq: [['dumbbell', 'mat'], ['dumbbell']], skill: 2, fatigue: 'moderate', repMin: 6, repMax: 15,
    stress: { shoulder: 1, elbow: 1 }, flags: F('lying_supine', 'floor_transition'),
    tags: ['shoulder_friendly', 'limited_rom'] }),
  ex({ id: 'trx_chest_press', name: 'לחיצת חזה ב-TRX', nameEn: 'TRX Chest Press',
    pattern: 'horizontal_push', primary: ['chest'], secondary: ['core_anterior', 'triceps'],
    eq: [['trx'], ['suspension_anchor']], skill: 3, fatigue: 'moderate', repMin: 6, repMax: 20, loadable: false,
    stress: { shoulder: 2, wrist: 1 }, flags: F('unstable', 'end_range_shoulder_ext') }),

  // ---------------------------------------------------------------- בידוד חזה
  ex({ id: 'pec_deck', name: 'פרפר במכונה', nameEn: 'Pec Deck',
    type: 'isolation', pattern: 'horizontal_push', primary: ['chest'],
    eq: [['pec_deck']], skill: 1, fatigue: 'low', repMin: 8, repMax: 25,
    stress: { shoulder: 2 }, flags: F('end_range_shoulder_ext', 'end_range_joint') }),
  ex({ id: 'cable_fly', name: 'פרפר בכבלים', nameEn: 'Cable Fly',
    type: 'isolation', pattern: 'horizontal_push', primary: ['chest'],
    eq: [['cable_crossover']], skill: 2, fatigue: 'low', repMin: 10, repMax: 25,
    stress: { shoulder: 2 }, flags: F('end_range_shoulder_ext') }),
  ex({ id: 'db_fly', name: 'פרפר עם משקולות', nameEn: 'Dumbbell Fly',
    type: 'isolation', pattern: 'horizontal_push', primary: ['chest'],
    eq: [['dumbbell', 'bench_flat']], skill: 3, fatigue: 'low', repMin: 8, repMax: 20,
    stress: { shoulder: 3 }, flags: F('end_range_shoulder_ext', 'lying_supine', 'end_range_joint') }),

  // ---------------------------------------------------------------- משיכה אופקית
  ex({ id: 'bb_row', name: 'חתירה במוט בהטיה', nameEn: 'Barbell Bent-over Row',
    pattern: 'horizontal_pull', primary: ['back_lats', 'back_upper'], secondary: ['biceps', 'core_posterior'],
    eq: [['barbell']], skill: 4, fatigue: 'high', repMin: 5, repMax: 15,
    stress: { lumbar: 3, hip: 1, elbow: 1, shoulder: 1 }, flags: F('grip_intensive', 'high_valsalva') }),
  ex({ id: 'db_row_1arm', name: 'חתירה עם משקולת יד אחת', nameEn: 'One-arm Dumbbell Row',
    pattern: 'horizontal_pull', primary: ['back_lats'], secondary: ['biceps', 'back_upper'],
    eq: [['dumbbell', 'bench_flat'], ['dumbbell']], unilateral: true, skill: 2, fatigue: 'moderate',
    repMin: 6, repMax: 20, stress: { lumbar: 1, shoulder: 1 }, tags: ['back_friendly'] }),
  ex({ id: 'chest_supported_row', name: 'חתירה בתמיכת חזה', nameEn: 'Chest-supported Row',
    pattern: 'horizontal_pull', primary: ['back_upper', 'back_lats'], secondary: ['delts_rear', 'biceps'],
    eq: [['dumbbell', 'bench_incline'], ['seated_row_machine']], skill: 1, fatigue: 'moderate',
    repMin: 8, repMax: 20, stress: { lumbar: 0, shoulder: 1 }, flags: F('lying_prone'),
    tags: ['back_friendly', 'beginner_friendly'] }),
  ex({ id: 'seated_cable_row', name: 'חתירה בישיבה בכבל', nameEn: 'Seated Cable Row',
    pattern: 'horizontal_pull', primary: ['back_lats', 'back_upper'], secondary: ['biceps'],
    eq: [['seated_row_machine'], ['cable_crossover']], skill: 1, fatigue: 'moderate',
    repMin: 8, repMax: 20, stress: { lumbar: 1 }, tags: ['beginner_friendly'] }),
  ex({ id: 'machine_row', name: 'חתירה במכונה', nameEn: 'Machine Row',
    pattern: 'horizontal_pull', primary: ['back_lats', 'back_upper'], secondary: ['biceps'],
    eq: [['seated_row_machine']], skill: 1, fatigue: 'moderate', repMin: 8, repMax: 22,
    stress: { lumbar: 0 }, tags: ['beginner_friendly', 'joint_friendly'] }),
  ex({ id: 'inverted_row', name: 'חתירה הפוכה (גוף)', nameEn: 'Inverted Row',
    pattern: 'horizontal_pull', primary: ['back_upper', 'back_lats'], secondary: ['biceps', 'core_anterior'],
    eq: [['smith_machine'], ['trx'], ['squat_rack', 'barbell'], ['suspension_anchor']],
    skill: 2, fatigue: 'moderate', repMin: 5, repMax: 20, loadable: false,
    stress: { shoulder: 1 }, flags: F('grip_intensive') }),
  ex({ id: 'trx_row', name: 'חתירה ב-TRX', nameEn: 'TRX Row',
    pattern: 'horizontal_pull', primary: ['back_upper'], secondary: ['biceps', 'core_anterior'],
    eq: [['trx'], ['suspension_anchor']], skill: 2, fatigue: 'low', repMin: 8, repMax: 25, loadable: false,
    stress: { shoulder: 1 }, tags: ['scalable'] }),
  ex({ id: 'landmine_row', name: 'חתירה בלנדמיין', nameEn: 'Landmine Row',
    pattern: 'horizontal_pull', primary: ['back_lats'], secondary: ['back_upper', 'biceps'],
    eq: [['landmine', 'barbell']], skill: 3, fatigue: 'high', repMin: 6, repMax: 15,
    stress: { lumbar: 2 } }),
  ex({ id: 'band_row', name: 'חתירה בגומייה', nameEn: 'Band Row',
    pattern: 'horizontal_pull', primary: ['back_upper'], secondary: ['biceps'],
    eq: [['resistance_band']], skill: 1, fatigue: 'low', repMin: 10, repMax: 30, loadable: false,
    tags: ['regression', 'rehab_friendly', 'no_equipment'] }),

  // ---------------------------------------------------------------- משיכה אנכית
  ex({ id: 'pullup', name: 'מתח באחיזה רחבה', nameEn: 'Pull-up',
    pattern: 'vertical_pull', primary: ['back_lats'], secondary: ['biceps', 'back_upper', 'core_anterior'],
    eq: [['pullup_bar']], skill: 4, fatigue: 'high', repMin: 3, repMax: 15, loadable: false,
    stress: { shoulder: 2, elbow: 2 }, flags: F('overhead', 'grip_intensive'), ceilingCm: 250 }),
  ex({ id: 'chinup', name: 'מתח באחיזה תחתונה', nameEn: 'Chin-up',
    pattern: 'vertical_pull', primary: ['back_lats'], secondary: ['biceps'],
    eq: [['pullup_bar']], skill: 4, fatigue: 'high', repMin: 3, repMax: 15, loadable: false,
    stress: { shoulder: 2, elbow: 2 }, flags: F('overhead', 'grip_intensive'), ceilingCm: 250 }),
  ex({ id: 'assisted_pullup', name: 'מתח בסיוע מכונה', nameEn: 'Assisted Pull-up',
    pattern: 'vertical_pull', primary: ['back_lats'], secondary: ['biceps'],
    eq: [['assisted_pullup_machine']], skill: 2, fatigue: 'moderate', repMin: 5, repMax: 15,
    stress: { shoulder: 2, elbow: 1 }, flags: F('overhead'), tags: ['regression'] }),
  ex({ id: 'lat_pulldown', name: 'פולי עליון', nameEn: 'Lat Pulldown',
    pattern: 'vertical_pull', primary: ['back_lats'], secondary: ['biceps', 'back_upper'],
    eq: [['lat_pulldown'], ['cable_crossover']], skill: 1, fatigue: 'moderate', repMin: 6, repMax: 20,
    stress: { shoulder: 1, elbow: 1 }, flags: F('overhead'), tags: ['beginner_friendly'] }),
  ex({ id: 'neutral_pulldown', name: 'פולי עליון אחיזה ניטרלית', nameEn: 'Neutral-grip Pulldown',
    pattern: 'vertical_pull', primary: ['back_lats'], secondary: ['biceps'],
    eq: [['lat_pulldown'], ['cable_crossover']], skill: 1, fatigue: 'moderate', repMin: 8, repMax: 20,
    stress: { shoulder: 1 }, flags: F('overhead'), tags: ['shoulder_friendly'] }),
  ex({ id: 'straight_arm_pulldown', name: 'פולאובר בכבל (זרוע ישרה)', nameEn: 'Straight-arm Pulldown',
    type: 'isolation', pattern: 'vertical_pull', primary: ['back_lats'],
    eq: [['cable_crossover'], ['lat_pulldown']], skill: 2, fatigue: 'low', repMin: 10, repMax: 25,
    stress: { shoulder: 1 } }),
  ex({ id: 'band_pulldown', name: 'פולי עליון בגומייה', nameEn: 'Band Lat Pulldown',
    pattern: 'vertical_pull', primary: ['back_lats'], secondary: ['biceps'],
    eq: [['resistance_band']], skill: 1, fatigue: 'low', repMin: 10, repMax: 25, loadable: false,
    flags: F('overhead'), tags: ['regression', 'no_equipment'] }),

  // ---------------------------------------------------------------- דחיפה אנכית
  ex({ id: 'bb_ohp', name: 'לחיצת כתפיים במוט בעמידה', nameEn: 'Barbell Overhead Press',
    pattern: 'vertical_push', primary: ['delts_front'], secondary: ['triceps', 'core_anterior', 'delts_side'],
    eq: [['barbell'], ['barbell', 'squat_rack']], skill: 3, fatigue: 'high', repMin: 4, repMax: 12,
    stress: { shoulder: 3, lumbar: 2, elbow: 1, wrist: 2 }, flags: F('overhead', 'spinal_loading', 'high_valsalva', 'weight_over_head_free'), ceilingCm: 250 }),
  ex({ id: 'db_shoulder_press', name: 'לחיצת כתפיים עם משקולות בישיבה', nameEn: 'Seated Dumbbell Shoulder Press',
    pattern: 'vertical_push', primary: ['delts_front'], secondary: ['triceps', 'delts_side'],
    eq: [['dumbbell', 'bench_incline'], ['dumbbell']], skill: 2, fatigue: 'moderate', repMin: 6, repMax: 18,
    stress: { shoulder: 2, elbow: 1 }, flags: F('overhead', 'weight_over_head_free') }),
  ex({ id: 'machine_shoulder_press', name: 'לחיצת כתפיים במכונה', nameEn: 'Machine Shoulder Press',
    pattern: 'vertical_push', primary: ['delts_front'], secondary: ['triceps'],
    eq: [['shoulder_press_machine']], skill: 1, fatigue: 'moderate', repMin: 8, repMax: 20,
    stress: { shoulder: 2 }, flags: F('overhead'), tags: ['beginner_friendly'] }),
  ex({ id: 'landmine_press', name: 'לחיצת לנדמיין', nameEn: 'Landmine Press',
    pattern: 'vertical_push', primary: ['delts_front'], secondary: ['triceps', 'core_anterior', 'chest'],
    eq: [['landmine', 'barbell']], unilateral: true, skill: 3, fatigue: 'moderate', repMin: 6, repMax: 15,
    stress: { shoulder: 1 }, tags: ['shoulder_friendly'] }),
  ex({ id: 'arnold_press', name: 'לחיצת ארנולד', nameEn: 'Arnold Press',
    pattern: 'vertical_push', primary: ['delts_front', 'delts_side'], secondary: ['triceps'],
    eq: [['dumbbell']], skill: 3, fatigue: 'moderate', repMin: 8, repMax: 15,
    stress: { shoulder: 3, elbow: 1 }, flags: F('overhead', 'weight_over_head_free') }),
  ex({ id: 'pike_pushup', name: 'שכיבות סמיכה פייק', nameEn: 'Pike Push-up',
    pattern: 'vertical_push', primary: ['delts_front'], secondary: ['triceps'],
    eq: [['bodyweight']], skill: 3, fatigue: 'moderate', repMin: 5, repMax: 15, loadable: false,
    stress: { shoulder: 2, wrist: 2 }, flags: F('overhead', 'wrist_extension_load', 'floor_transition', 'head_below_heart') }),

  // ---------------------------------------------------------------- כתף — בידוד
  ex({ id: 'lateral_raise_db', name: 'הרחקות צד עם משקולות', nameEn: 'Dumbbell Lateral Raise',
    type: 'isolation', pattern: 'shoulder_isolation', primary: ['delts_side'],
    eq: [['dumbbell']], plane: 'frontal', skill: 2, fatigue: 'low', repMin: 10, repMax: 25,
    stress: { shoulder: 1 } }),
  ex({ id: 'lateral_raise_cable', name: 'הרחקות צד בכבל', nameEn: 'Cable Lateral Raise',
    type: 'isolation', pattern: 'shoulder_isolation', primary: ['delts_side'],
    eq: [['cable_crossover']], plane: 'frontal', unilateral: true, skill: 2, fatigue: 'low',
    repMin: 10, repMax: 25, stress: { shoulder: 1 } }),
  ex({ id: 'lateral_raise_band', name: 'הרחקות צד בגומייה', nameEn: 'Band Lateral Raise',
    type: 'isolation', pattern: 'shoulder_isolation', primary: ['delts_side'],
    eq: [['resistance_band'], ['mini_band']], plane: 'frontal', skill: 1, fatigue: 'low',
    repMin: 12, repMax: 30, loadable: false, tags: ['regression', 'rehab_friendly'] }),
  ex({ id: 'rear_delt_fly_db', name: 'פרפר אחורי בהטיה', nameEn: 'Bent-over Rear Delt Fly',
    type: 'isolation', pattern: 'shoulder_isolation', primary: ['delts_rear'], secondary: ['back_upper'],
    eq: [['dumbbell']], plane: 'transverse', skill: 2, fatigue: 'low', repMin: 12, repMax: 25,
    stress: { lumbar: 1, shoulder: 1 } }),
  ex({ id: 'rear_delt_machine', name: 'פרפר אחורי במכונה', nameEn: 'Reverse Pec Deck',
    type: 'isolation', pattern: 'shoulder_isolation', primary: ['delts_rear'], secondary: ['back_upper'],
    eq: [['rear_delt_machine'], ['pec_deck']], plane: 'transverse', skill: 1, fatigue: 'low',
    repMin: 12, repMax: 25, tags: ['posture'] }),
  ex({ id: 'face_pull', name: 'פייס-פול בכבל', nameEn: 'Cable Face Pull',
    type: 'isolation', pattern: 'shoulder_isolation', primary: ['delts_rear'], secondary: ['back_upper'],
    eq: [['cable_crossover'], ['resistance_band']], plane: 'transverse', skill: 2, fatigue: 'low',
    repMin: 12, repMax: 25, tags: ['posture', 'shoulder_health', 'rehab_friendly'] }),
  ex({ id: 'external_rotation_band', name: 'סיבוב חיצוני בגומייה', nameEn: 'Band External Rotation',
    type: 'isolation', pattern: 'shoulder_isolation', primary: ['delts_rear'],
    eq: [['resistance_band'], ['mini_band'], ['cable_crossover']], plane: 'transverse', unilateral: true,
    skill: 1, fatigue: 'low', repMin: 12, repMax: 25, loadable: false,
    tags: ['rehab_friendly', 'shoulder_health'] }),
  ex({ id: 'ytw_prone', name: 'Y-T-W בשכיבה על הבטן', nameEn: 'Prone Y-T-W Raise',
    type: 'isolation', pattern: 'shoulder_isolation', primary: ['back_upper', 'delts_rear'],
    eq: [['bench_incline'], ['mat'], ['bodyweight']], skill: 2, fatigue: 'low', repMin: 8, repMax: 20,
    loadable: false, flags: F('lying_prone', 'overhead'), tags: ['posture', 'rehab_friendly'] }),

  // ---------------------------------------------------------------- סקוואט
  ex({ id: 'bb_back_squat', name: 'סקוואט מוט על הגב', nameEn: 'Barbell Back Squat',
    pattern: 'squat', primary: ['quads', 'glutes'], secondary: ['core_posterior', 'adductors'],
    eq: [['barbell', 'squat_rack'], ['barbell', 'power_rack']], skill: 4, fatigue: 'very_high',
    repMin: 3, repMax: 15, stress: { knee: 2, lumbar: 3, hip: 2, ankle: 2, shoulder: 1 },
    flags: F('spinal_loading', 'deep_knee_flexion', 'high_valsalva', 'axial_neck_load') }),
  ex({ id: 'bb_front_squat', name: 'סקוואט קדמי', nameEn: 'Front Squat',
    pattern: 'squat', primary: ['quads'], secondary: ['glutes', 'core_anterior'],
    eq: [['barbell', 'squat_rack'], ['barbell', 'power_rack']], skill: 5, fatigue: 'very_high',
    repMin: 3, repMax: 12, stress: { knee: 3, lumbar: 2, wrist: 2, shoulder: 2 },
    flags: F('spinal_loading', 'deep_knee_flexion', 'high_valsalva') }),
  ex({ id: 'goblet_squat', name: 'סקוואט גובלט', nameEn: 'Goblet Squat',
    pattern: 'squat', primary: ['quads', 'glutes'], secondary: ['core_anterior'],
    eq: [['dumbbell'], ['kettlebell']], skill: 2, fatigue: 'high', repMin: 6, repMax: 20,
    stress: { knee: 2, lumbar: 1, hip: 1, ankle: 1 }, flags: F('deep_knee_flexion'),
    tags: ['beginner_friendly'] }),
  ex({ id: 'leg_press', name: 'לחיצת רגליים', nameEn: 'Leg Press',
    pattern: 'squat', primary: ['quads', 'glutes'], secondary: ['adductors'],
    eq: [['leg_press']], skill: 1, fatigue: 'high', repMin: 6, repMax: 25,
    stress: { knee: 2, lumbar: 1, hip: 1 }, flags: F('deep_hip_flexion'),
    tags: ['beginner_friendly', 'back_friendly'] }),
  ex({ id: 'hack_squat', name: 'האק סקוואט', nameEn: 'Hack Squat',
    pattern: 'squat', primary: ['quads'], secondary: ['glutes'],
    eq: [['hack_squat']], skill: 2, fatigue: 'high', repMin: 6, repMax: 20,
    stress: { knee: 3, lumbar: 1 }, flags: F('deep_knee_flexion', 'spinal_loading') }),
  ex({ id: 'smith_squat', name: 'סקוואט בסמית', nameEn: 'Smith Machine Squat',
    pattern: 'squat', primary: ['quads', 'glutes'],
    eq: [['smith_machine']], skill: 2, fatigue: 'high', repMin: 6, repMax: 20,
    stress: { knee: 2, lumbar: 2 }, flags: F('spinal_loading', 'deep_knee_flexion') }),
  ex({ id: 'box_squat', name: 'סקוואט לספסל', nameEn: 'Box Squat',
    pattern: 'squat', primary: ['quads', 'glutes'],
    // הספסל מגדיר את העומק, לא את ההתנגדות — זו גרסת משקל גוף
    eq: [['bench_flat'], ['plyo_box'], ['step']], skill: 1, fatigue: 'moderate', repMin: 8, repMax: 20,
    loadable: false, stress: { knee: 1, lumbar: 1 }, tags: ['regression', 'beginner_friendly', 'knee_friendly'] }),
  ex({ id: 'wall_sit', name: 'ישיבת קיר', nameEn: 'Wall Sit',
    type: 'isolation', pattern: 'squat', primary: ['quads'],
    eq: [['bodyweight']], skill: 1, fatigue: 'low', repMin: 20, repMax: 60, loadable: false,
    stress: { knee: 1 }, tags: ['regression', 'isometric', 'rehab_friendly'] }),

  // ---------------------------------------------------------------- מכרע / חד-צדדי
  ex({ id: 'split_squat', name: 'סקוואט בולגרי', nameEn: 'Bulgarian Split Squat',
    pattern: 'lunge', primary: ['quads', 'glutes'], secondary: ['adductors', 'core_lateral'],
    eq: [['dumbbell', 'bench_flat'], ['bench_flat'], ['dumbbell', 'step']], unilateral: true,
    skill: 3, fatigue: 'high', repMin: 6, repMax: 20,
    stress: { knee: 2, hip: 2, ankle: 1 }, flags: F('balance', 'deep_knee_flexion') }),
  ex({ id: 'walking_lunge', name: 'מכרעים בהליכה', nameEn: 'Walking Lunge',
    pattern: 'lunge', primary: ['quads', 'glutes'], secondary: ['hamstrings'],
    eq: [['dumbbell'], ['bodyweight'], ['kettlebell']], unilateral: true, skill: 2, fatigue: 'high',
    repMin: 8, repMax: 24, stress: { knee: 2, hip: 1 }, flags: F('balance'), space: 'large' }),
  ex({ id: 'reverse_lunge', name: 'מכרע לאחור', nameEn: 'Reverse Lunge',
    pattern: 'lunge', primary: ['glutes', 'quads'], secondary: ['hamstrings'],
    eq: [['bodyweight'], ['dumbbell']], unilateral: true, skill: 2, fatigue: 'moderate',
    repMin: 8, repMax: 20, stress: { knee: 1, hip: 1 }, flags: F('balance'),
    tags: ['knee_friendly'] }),
  ex({ id: 'step_up', name: 'עלייה על סטפ', nameEn: 'Step-up',
    pattern: 'lunge', primary: ['quads', 'glutes'],
    // הסטפ הוא המשטח, לא ההתנגדות. עלייה על סטפ עם משקולות מיוצגת
    // בתרגילים נפרדים (מכרעים, סקוואט בולגרי) שיש להם ציוד מעמיס
    eq: [['step'], ['plyo_box'], ['bench_flat']], unilateral: true, skill: 2, fatigue: 'moderate',
    repMin: 8, repMax: 20, loadable: false, stress: { knee: 1, hip: 1 }, flags: F('balance') }),
  ex({ id: 'lateral_lunge', name: 'מכרע צידי', nameEn: 'Lateral Lunge',
    pattern: 'lunge', primary: ['adductors', 'glutes'], secondary: ['quads'],
    eq: [['bodyweight'], ['dumbbell'], ['kettlebell']], plane: 'frontal', unilateral: true,
    skill: 3, fatigue: 'moderate', repMin: 8, repMax: 16, stress: { knee: 1, hip: 2 },
    flags: F('balance', 'hip_adduction_load') }),

  // ---------------------------------------------------------------- הינג' / אחורי ירך
  ex({ id: 'conventional_deadlift', name: 'דדליפט קונבנציונלי', nameEn: 'Conventional Deadlift',
    pattern: 'hinge', primary: ['hamstrings', 'glutes'], secondary: ['back_posterior', 'core_posterior', 'forearms', 'back_upper'],
    eq: [['barbell']], skill: 5, fatigue: 'very_high', repMin: 1, repMax: 10,
    stress: { lumbar: 3, hip: 2, knee: 1, elbow: 1 },
    flags: F('spinal_loading', 'high_valsalva', 'grip_intensive'), noisy: true }),
  ex({ id: 'trap_bar_deadlift', name: 'דדליפט טראפ-בר', nameEn: 'Trap Bar Deadlift',
    pattern: 'hinge', primary: ['glutes', 'quads'], secondary: ['hamstrings', 'core_posterior'],
    eq: [['trap_bar']], skill: 3, fatigue: 'very_high', repMin: 3, repMax: 12,
    stress: { lumbar: 2, hip: 2, knee: 1 }, flags: F('spinal_loading', 'grip_intensive'),
    tags: ['back_friendly'], noisy: true }),
  ex({ id: 'rdl_bb', name: 'רומנית במוט', nameEn: 'Barbell Romanian Deadlift',
    pattern: 'hinge', primary: ['hamstrings', 'glutes'], secondary: ['core_posterior'],
    eq: [['barbell']], skill: 3, fatigue: 'high', repMin: 5, repMax: 15,
    stress: { lumbar: 2, hip: 2 }, flags: F('spinal_loading', 'grip_intensive') }),
  ex({ id: 'rdl_db', name: 'רומנית עם משקולות', nameEn: 'Dumbbell Romanian Deadlift',
    pattern: 'hinge', primary: ['hamstrings', 'glutes'],
    eq: [['dumbbell'], ['kettlebell']], skill: 2, fatigue: 'moderate', repMin: 8, repMax: 18,
    stress: { lumbar: 2, hip: 1 } }),
  ex({ id: 'single_leg_rdl', name: 'רומנית על רגל אחת', nameEn: 'Single-leg RDL',
    pattern: 'hinge', primary: ['hamstrings', 'glutes'], secondary: ['core_lateral'],
    eq: [['dumbbell'], ['kettlebell'], ['bodyweight']], unilateral: true, skill: 4, fatigue: 'moderate',
    repMin: 6, repMax: 15, stress: { lumbar: 1, hip: 1 }, flags: F('balance') }),
  ex({ id: 'hip_thrust', name: 'היפ תראסט', nameEn: 'Barbell Hip Thrust',
    pattern: 'hinge', primary: ['glutes'], secondary: ['hamstrings'],
    eq: [['barbell', 'bench_flat'], ['hip_thrust_machine'], ['dumbbell', 'bench_flat']],
    skill: 2, fatigue: 'high', repMin: 6, repMax: 20, stress: { hip: 1, lumbar: 1 },
    tags: ['glute_focus'] }),
  ex({ id: 'glute_bridge', name: 'גשר ישבן', nameEn: 'Glute Bridge',
    pattern: 'hinge', primary: ['glutes'], secondary: ['hamstrings'],
    eq: [['bodyweight'], ['mat'], ['mini_band']], skill: 1, fatigue: 'low', repMin: 10, repMax: 25,
    flags: F('lying_supine', 'floor_transition'), tags: ['rehab_friendly', 'beginner_friendly'] }),
  ex({ id: 'leg_curl_lying', name: 'כפיפת ברכיים בשכיבה', nameEn: 'Lying Leg Curl',
    type: 'isolation', pattern: 'hinge', primary: ['hamstrings'],
    eq: [['leg_curl_lying']], skill: 1, fatigue: 'low', repMin: 8, repMax: 20,
    stress: { knee: 1 }, flags: F('lying_prone') }),
  ex({ id: 'leg_curl_seated', name: 'כפיפת ברכיים בישיבה', nameEn: 'Seated Leg Curl',
    type: 'isolation', pattern: 'hinge', primary: ['hamstrings'],
    eq: [['leg_curl_seated']], skill: 1, fatigue: 'low', repMin: 8, repMax: 20, stress: { knee: 1 } }),
  ex({ id: 'nordic_curl', name: 'נורדיק קרל', nameEn: 'Nordic Hamstring Curl',
    pattern: 'hinge', primary: ['hamstrings'],
    eq: [['ghd'], ['mat']], skill: 5, fatigue: 'high', repMin: 3, repMax: 8, loadable: false,
    stress: { knee: 2 }, flags: F('floor_transition', 'end_range_joint') }),
  ex({ id: 'back_extension', name: 'יישור גב בספסל רומי', nameEn: 'Back Extension',
    pattern: 'hinge', primary: ['core_posterior', 'glutes'], secondary: ['hamstrings'],
    eq: [['back_extension_bench'], ['roman_chair'], ['ghd']], skill: 2, fatigue: 'moderate',
    repMin: 8, repMax: 20, stress: { lumbar: 2 }, flags: F('lying_prone') }),
  ex({ id: 'kb_swing', name: 'סווינג קטלבל', nameEn: 'Kettlebell Swing',
    pattern: 'hinge', primary: ['glutes', 'hamstrings'], secondary: ['core_posterior'],
    eq: [['kettlebell']], skill: 4, fatigue: 'high', repMin: 10, repMax: 25,
    stress: { lumbar: 2, hip: 1, cardio: 2 }, flags: F('ballistic', 'grip_intensive', 'rapid_position_change'),
    tags: ['conditioning'], space: 'medium', noisy: true }),

  // ---------------------------------------------------------------- ירך: הרחקה/קירוב, תאומים
  ex({ id: 'abduction_machine', name: 'הרחקת ירך במכונה', nameEn: 'Hip Abduction Machine',
    type: 'isolation', pattern: 'hip_abduction', primary: ['abductors', 'glutes'],
    eq: [['abduction_machine']], plane: 'frontal', skill: 1, fatigue: 'low', repMin: 12, repMax: 25 }),
  ex({ id: 'adduction_machine', name: 'קירוב ירך במכונה', nameEn: 'Hip Adduction Machine',
    type: 'isolation', pattern: 'hip_abduction', primary: ['adductors'],
    eq: [['adduction_machine']], plane: 'frontal', skill: 1, fatigue: 'low', repMin: 12, repMax: 25, flags: F('hip_adduction_load')}),
  ex({ id: 'band_clamshell', name: 'קלאם-של בגומייה', nameEn: 'Banded Clamshell',
    type: 'isolation', pattern: 'hip_abduction', primary: ['abductors', 'glutes'],
    eq: [['mini_band'], ['bodyweight']], plane: 'transverse', unilateral: true, skill: 1, fatigue: 'low',
    repMin: 12, repMax: 30, loadable: false, flags: F('floor_transition'),
    tags: ['rehab_friendly', 'knee_friendly'] }),
  ex({ id: 'cable_kickback', name: 'בעיטת ישבן בכבל', nameEn: 'Cable Glute Kickback',
    type: 'isolation', pattern: 'hinge', primary: ['glutes'],
    eq: [['cable_crossover'], ['glute_kickback_machine']], unilateral: true, skill: 2, fatigue: 'low',
    repMin: 12, repMax: 25 }),
  ex({ id: 'standing_calf_raise', name: 'הרמת עקבים בעמידה', nameEn: 'Standing Calf Raise',
    type: 'isolation', pattern: 'calf', primary: ['calves'],
    eq: [['calf_raise_machine'], ['smith_machine'], ['dumbbell'], ['step'], ['bodyweight']],
    skill: 1, fatigue: 'low', repMin: 10, repMax: 25, stress: { ankle: 1 } }),
  ex({ id: 'seated_calf_raise', name: 'הרמת עקבים בישיבה', nameEn: 'Seated Calf Raise',
    type: 'isolation', pattern: 'calf', primary: ['calves'],
    eq: [['calf_raise_machine'], ['dumbbell', 'bench_flat']], skill: 1, fatigue: 'low',
    repMin: 12, repMax: 25, stress: { ankle: 1 } }),

  // ---------------------------------------------------------------- יד קדמית
  ex({ id: 'db_curl', name: 'כפיפת מרפקים עם משקולות', nameEn: 'Dumbbell Curl',
    type: 'isolation', pattern: 'elbow_flexion', primary: ['biceps'], secondary: ['forearms'],
    eq: [['dumbbell']], skill: 1, fatigue: 'low', repMin: 8, repMax: 20, stress: { elbow: 1 } }),
  ex({ id: 'hammer_curl', name: 'כפיפת פטיש', nameEn: 'Hammer Curl',
    type: 'isolation', pattern: 'elbow_flexion', primary: ['biceps', 'forearms'],
    eq: [['dumbbell']], skill: 1, fatigue: 'low', repMin: 8, repMax: 20, stress: { elbow: 1 },
    tags: ['elbow_friendly'] }),
  ex({ id: 'ez_curl', name: 'כפיפת מרפקים במוט EZ', nameEn: 'EZ-bar Curl',
    type: 'isolation', pattern: 'elbow_flexion', primary: ['biceps'],
    eq: [['ez_bar'], ['barbell'], ['fixed_barbell']], skill: 1, fatigue: 'low', repMin: 8, repMax: 15,
    stress: { elbow: 2, wrist: 1 } }),
  ex({ id: 'cable_curl', name: 'כפיפת מרפקים בכבל', nameEn: 'Cable Curl',
    type: 'isolation', pattern: 'elbow_flexion', primary: ['biceps'],
    eq: [['cable_crossover']], skill: 1, fatigue: 'low', repMin: 10, repMax: 20, stress: { elbow: 1 } }),
  ex({ id: 'preacher_curl', name: 'כפיפת מרפקים בסקוט', nameEn: 'Preacher Curl',
    type: 'isolation', pattern: 'elbow_flexion', primary: ['biceps'],
    eq: [['preacher_curl_bench', 'ez_bar'], ['preacher_curl_bench', 'dumbbell']], skill: 2, fatigue: 'low',
    repMin: 8, repMax: 15, stress: { elbow: 2 } }),
  ex({ id: 'band_curl', name: 'כפיפת מרפקים בגומייה', nameEn: 'Band Curl',
    type: 'isolation', pattern: 'elbow_flexion', primary: ['biceps'],
    eq: [['resistance_band']], skill: 1, fatigue: 'low', repMin: 12, repMax: 25, loadable: false, tags: ['regression']}),

  // ---------------------------------------------------------------- יד אחורית
  ex({ id: 'cable_pushdown', name: 'פשיטת מרפקים בפולי', nameEn: 'Cable Triceps Pushdown',
    type: 'isolation', pattern: 'elbow_extension', primary: ['triceps'],
    eq: [['cable_crossover'], ['lat_pulldown']], skill: 1, fatigue: 'low', repMin: 10, repMax: 20,
    stress: { elbow: 1 } }),
  ex({ id: 'overhead_ext', name: 'פשיטת מרפקים מעל הראש', nameEn: 'Overhead Triceps Extension',
    type: 'isolation', pattern: 'elbow_extension', primary: ['triceps'],
    eq: [['dumbbell'], ['cable_crossover'], ['ez_bar']], skill: 2, fatigue: 'low', repMin: 8, repMax: 18,
    stress: { elbow: 2, shoulder: 1 }, flags: F('overhead', 'weight_over_head_free') }),
  ex({ id: 'skullcrusher', name: 'סקאל-קראשר', nameEn: 'Skullcrusher',
    type: 'isolation', pattern: 'elbow_extension', primary: ['triceps'],
    eq: [['ez_bar', 'bench_flat'], ['dumbbell', 'bench_flat']], skill: 2, fatigue: 'low',
    repMin: 8, repMax: 15, stress: { elbow: 3 }, flags: F('lying_supine') }),
  ex({ id: 'dips', name: 'מקבילים', nameEn: 'Parallel Bar Dips',
    pattern: 'elbow_extension', primary: ['triceps', 'chest'], secondary: ['delts_front'],
    eq: [['dip_station']], skill: 4, fatigue: 'high', repMin: 4, repMax: 15, loadable: false,
    stress: { shoulder: 3, elbow: 2, wrist: 1 }, flags: F('end_range_shoulder_ext', 'grip_intensive', 'end_range_joint') }),
  ex({ id: 'bench_dip', name: 'מקבילים על ספסל', nameEn: 'Bench Dip',
    pattern: 'elbow_extension', primary: ['triceps'],
    eq: [['bench_flat'], ['step']], skill: 2, fatigue: 'moderate', repMin: 8, repMax: 20, loadable: false,
    stress: { shoulder: 3, elbow: 1, wrist: 2 }, flags: F('end_range_shoulder_ext', 'end_range_joint') }),
  ex({ id: 'close_grip_pushup', name: 'שכיבות סמיכה אחיזה צרה', nameEn: 'Close-grip Push-up',
    pattern: 'elbow_extension', primary: ['triceps'], secondary: ['chest'],
    eq: [['bodyweight']], skill: 2, fatigue: 'moderate', repMin: 5, repMax: 20, loadable: false,
    stress: { wrist: 2, elbow: 1 }, flags: F('wrist_extension_load', 'floor_transition') }),

  // ---------------------------------------------------------------- ליבה
  ex({ id: 'plank', name: 'פלאנק', nameEn: 'Front Plank',
    type: 'isolation', pattern: 'core_antiextension', primary: ['core_anterior'],
    eq: [['bodyweight'], ['mat']], skill: 1, fatigue: 'low', repMin: 20, repMax: 90, loadable: false,
    stress: { shoulder: 1, lumbar: 0 }, flags: F('floor_transition'), tags: ['isometric'] }),
  ex({ id: 'side_plank', name: 'פלאנק צד', nameEn: 'Side Plank',
    type: 'isolation', pattern: 'core_antilateralflexion', primary: ['core_lateral'],
    eq: [['bodyweight'], ['mat']], plane: 'frontal', unilateral: true, skill: 2, fatigue: 'low',
    repMin: 15, repMax: 60, loadable: false, stress: { shoulder: 1 }, flags: F('floor_transition'),
    tags: ['isometric', 'back_friendly'] }),
  ex({ id: 'dead_bug', name: 'דד-באג', nameEn: 'Dead Bug',
    type: 'isolation', pattern: 'core_antiextension', primary: ['core_anterior'],
    eq: [['bodyweight'], ['mat']], skill: 2, fatigue: 'low', repMin: 8, repMax: 20, loadable: false,
    flags: F('lying_supine', 'floor_transition'), tags: ['rehab_friendly', 'back_friendly'] }),
  ex({ id: 'bird_dog', name: 'ברד-דוג', nameEn: 'Bird Dog',
    type: 'isolation', pattern: 'core_antirotation', primary: ['core_posterior'], secondary: ['glutes'],
    eq: [['bodyweight'], ['mat']], skill: 1, fatigue: 'low', repMin: 8, repMax: 16, loadable: false,
    flags: F('floor_transition'), tags: ['rehab_friendly', 'back_friendly'] }),
  ex({ id: 'pallof_press', name: 'פאלוף פרס', nameEn: 'Pallof Press',
    type: 'isolation', pattern: 'core_antirotation', primary: ['core_lateral', 'core_anterior'],
    eq: [['cable_crossover'], ['resistance_band']], plane: 'transverse', skill: 2, fatigue: 'low',
    repMin: 8, repMax: 20, tags: ['back_friendly'] }),
  ex({ id: 'cable_crunch', name: 'כפיפת בטן בכבל', nameEn: 'Cable Crunch',
    type: 'isolation', pattern: 'core_flexion', primary: ['core_anterior'],
    eq: [['cable_crossover'], ['lat_pulldown']], skill: 2, fatigue: 'low', repMin: 10, repMax: 25,
    stress: { lumbar: 2 }, flags: F('spinal_flexion') }),
  ex({ id: 'hanging_leg_raise', name: 'הרמת רגליים בתלייה', nameEn: 'Hanging Leg Raise',
    type: 'isolation', pattern: 'core_flexion', primary: ['core_anterior'],
    eq: [['pullup_bar'], ['roman_chair']], skill: 4, fatigue: 'moderate', repMin: 5, repMax: 20,
    loadable: false, stress: { lumbar: 1, shoulder: 1 }, flags: F('grip_intensive', 'spinal_flexion'), ceilingCm: 250 }),
  ex({ id: 'crunch', name: 'כפיפות בטן', nameEn: 'Crunch',
    type: 'isolation', pattern: 'core_flexion', primary: ['core_anterior'],
    eq: [['bodyweight'], ['mat'], ['ab_machine']], skill: 1, fatigue: 'low', repMin: 12, repMax: 30,
    loadable: false, stress: { lumbar: 2, neck: 1 }, flags: F('spinal_flexion', 'lying_supine', 'floor_transition') }),
  ex({ id: 'ab_wheel', name: 'גלגל בטן', nameEn: 'Ab Wheel Rollout',
    type: 'isolation', pattern: 'core_antiextension', primary: ['core_anterior'],
    eq: [['ab_wheel'], ['barbell', 'weight_plate']], skill: 4, fatigue: 'moderate', repMin: 5, repMax: 15,
    loadable: false, stress: { lumbar: 2, shoulder: 1 }, flags: F('floor_transition', 'overhead') }),
  ex({ id: 'farmer_carry', name: 'הליכת חקלאי', nameEn: 'Farmer Carry',
    type: 'carry', pattern: 'carry', primary: ['core_lateral', 'forearms'], secondary: ['back_upper', 'glutes'],
    eq: [['dumbbell'], ['kettlebell']], skill: 1, fatigue: 'moderate', repMin: 20, repMax: 60,
    stress: { lumbar: 1 }, flags: F('grip_intensive'), tags: ['functional'], space: 'large' }),
  ex({ id: 'suitcase_carry', name: 'הליכת מזוודה (צד אחד)', nameEn: 'Suitcase Carry',
    type: 'carry', pattern: 'carry', primary: ['core_lateral'], secondary: ['forearms'],
    eq: [['dumbbell'], ['kettlebell']], plane: 'frontal', unilateral: true, skill: 2, fatigue: 'moderate',
    repMin: 20, repMax: 60, flags: F('grip_intensive'), tags: ['functional', 'back_friendly'], space: 'large' }),

  // ---------------------------------------------------------------- כוח מתפרץ
  ex({ id: 'box_jump', name: 'קפיצה לקופסה', nameEn: 'Box Jump',
    pattern: 'squat', primary: ['quads', 'glutes'],
    eq: [['plyo_box']], skill: 3, fatigue: 'high', repMin: 3, repMax: 8, loadable: false,
    stress: { knee: 2, ankle: 2 }, flags: F('impact', 'ballistic', 'rapid_position_change'), tags: ['power'], space: 'medium', ceilingCm: 260, noisy: true }),
  ex({ id: 'med_ball_slam', name: 'סלאם כדור כוח', nameEn: 'Medicine Ball Slam',
    pattern: 'conditioning', primary: ['core_anterior'], secondary: ['back_lats'],
    eq: [['slam_ball'], ['medicine_ball']], skill: 2, fatigue: 'high', repMin: 6, repMax: 15,
    loadable: false, stress: { lumbar: 1, shoulder: 1, cardio: 2 },
    flags: F('overhead', 'ballistic', 'spinal_flexion', 'rapid_position_change'), tags: ['power', 'conditioning'], space: 'medium', ceilingCm: 260, noisy: true }),
  ex({ id: 'med_ball_rotational_throw', name: 'זריקת כדור סיבובית', nameEn: 'Rotational Med Ball Throw',
    pattern: 'core_antirotation', primary: ['core_lateral'], secondary: ['glutes'],
    eq: [['medicine_ball'], ['slam_ball']], plane: 'transverse', unilateral: true, skill: 3,
    fatigue: 'moderate', repMin: 5, repMax: 12, loadable: false,
    stress: { lumbar: 1 }, flags: F('ballistic', 'spinal_rotation'), tags: ['power'], space: 'medium', noisy: true }),
  ex({ id: 'kb_clean', name: 'קלין קטלבל', nameEn: 'Kettlebell Clean',
    pattern: 'hinge', primary: ['glutes', 'hamstrings'], secondary: ['back_upper', 'forearms'],
    eq: [['kettlebell']], unilateral: true, skill: 5, fatigue: 'high', repMin: 5, repMax: 12,
    stress: { lumbar: 2, wrist: 2, cardio: 2 }, flags: F('ballistic', 'grip_intensive'), tags: ['power'] }),

  // ---------------------------------------------------------------- קונדישן
  ex({ id: 'rower_intervals', name: 'אינטרוולים במשוטים', nameEn: 'Rowing Intervals',
    type: 'conditioning', pattern: 'conditioning', primary: ['back_upper', 'quads'], secondary: ['hamstrings'],
    eq: [['rower']], skill: 3, fatigue: 'high', repMin: 30, repMax: 300, loadable: false,
    stress: { lumbar: 1, cardio: 3 }, tags: ['low_impact'] }),
  ex({ id: 'bike_intervals', name: 'אינטרוולים באופניים', nameEn: 'Bike Intervals',
    type: 'conditioning', pattern: 'conditioning', primary: ['quads'],
    eq: [['bike'], ['air_bike']], skill: 1, fatigue: 'moderate', repMin: 30, repMax: 600, loadable: false,
    stress: { knee: 1, cardio: 3 }, tags: ['low_impact', 'joint_friendly'] }),
  ex({ id: 'treadmill_incline_walk', name: 'הליכה בשיפוע', nameEn: 'Incline Treadmill Walk',
    type: 'conditioning', pattern: 'conditioning', primary: ['glutes', 'calves'],
    eq: [['treadmill']], skill: 1, fatigue: 'low', repMin: 300, repMax: 2400, loadable: false,
    stress: { cardio: 2, ankle: 1 }, tags: ['low_impact', 'fat_loss'] }),
  ex({ id: 'ski_erg', name: 'סקי-ארג', nameEn: 'Ski Erg',
    type: 'conditioning', pattern: 'conditioning', primary: ['back_lats', 'core_anterior'],
    eq: [['ski_erg']], skill: 2, fatigue: 'high', repMin: 30, repMax: 300, loadable: false,
    stress: { cardio: 3, shoulder: 1 }, flags: F('overhead'), ceilingCm: 250 }),
  ex({ id: 'battle_rope', name: 'חבלות קרב', nameEn: 'Battle Ropes',
    type: 'conditioning', pattern: 'conditioning', primary: ['delts_front', 'core_anterior'],
    eq: [['battle_rope']], skill: 2, fatigue: 'high', repMin: 20, repMax: 60, loadable: false,
    stress: { shoulder: 1, cardio: 3 }, flags: F('grip_intensive'), space: 'large', noisy: true }),
  ex({ id: 'sled_push', name: 'דחיפת מזחלת', nameEn: 'Sled Push',
    type: 'conditioning', pattern: 'conditioning', primary: ['quads', 'glutes'], secondary: ['calves'],
    eq: [['sled']], skill: 1, fatigue: 'high', repMin: 15, repMax: 60,
    stress: { cardio: 3, knee: 1 }, tags: ['joint_friendly', 'no_eccentric'], space: 'large', noisy: true }),
  ex({ id: 'jump_rope', name: 'קפיצה בחבל', nameEn: 'Jump Rope',
    type: 'conditioning', pattern: 'conditioning', primary: ['calves'],
    eq: [['jump_rope']], skill: 3, fatigue: 'moderate', repMin: 30, repMax: 180, loadable: false,
    stress: { ankle: 2, knee: 1, cardio: 3 }, flags: F('impact', 'rapid_position_change'), space: 'medium', ceilingCm: 270, noisy: true }),
  ex({ id: 'stair_climber', name: 'מדרגות', nameEn: 'Stair Climber',
    type: 'conditioning', pattern: 'conditioning', primary: ['glutes', 'quads'],
    eq: [['stair_climber']], skill: 1, fatigue: 'moderate', repMin: 300, repMax: 1800, loadable: false,
    stress: { cardio: 3, knee: 1 } }),

  // ---------------------------------------------------------------- ניידות / חימום
  ex({ id: 'hip_flexor_stretch', name: 'מתיחת כופפי ירך', nameEn: 'Couch/Hip Flexor Stretch',
    type: 'mobility', pattern: 'mobility', primary: ['hip'], eq: [['mat'], ['bodyweight']],
    skill: 1, fatigue: 'low', repMin: 20, repMax: 60, loadable: false, tags: ['warmup', 'posture'], flags: F('end_range_joint')}),
  ex({ id: 'thoracic_rotation', name: 'סיבוב חזי', nameEn: 'Thoracic Rotation',
    type: 'mobility', pattern: 'mobility', primary: ['core_posterior'], eq: [['mat'], ['bodyweight'], ['foam_roller']],
    plane: 'transverse', skill: 1, fatigue: 'low', repMin: 6, repMax: 12, loadable: false,
    tags: ['warmup', 'posture', 'shoulder_health'] }),
  ex({ id: 'ankle_mobility', name: 'ניידות קרסול', nameEn: 'Ankle Dorsiflexion Drill',
    type: 'mobility', pattern: 'mobility', primary: ['ankle'], eq: [['bodyweight']],
    skill: 1, fatigue: 'low', repMin: 8, repMax: 15, loadable: false, tags: ['warmup'] }),
  ex({ id: 'cat_cow', name: 'חתול-פרה', nameEn: 'Cat-Cow',
    type: 'mobility', pattern: 'mobility', primary: ['core_posterior'], eq: [['mat'], ['bodyweight']],
    skill: 1, fatigue: 'low', repMin: 6, repMax: 12, loadable: false,
    flags: F('floor_transition'), tags: ['warmup', 'back_friendly'] }),
  ex({ id: 'band_pull_apart', name: 'פתיחת גומייה', nameEn: 'Band Pull-apart',
    type: 'mobility', pattern: 'shoulder_isolation', primary: ['delts_rear', 'back_upper'],
    eq: [['resistance_band'], ['mini_band']], plane: 'transverse', skill: 1, fatigue: 'low',
    repMin: 12, repMax: 25, loadable: false, tags: ['warmup', 'posture', 'shoulder_health'] }),
  ex({ id: 'glute_activation_walk', name: 'הליכת גומייה (מונסטר ווק)', nameEn: 'Banded Monster Walk',
    type: 'mobility', pattern: 'hip_abduction', primary: ['abductors', 'glutes'],
    eq: [['mini_band']], plane: 'frontal', skill: 1, fatigue: 'low', repMin: 10, repMax: 20,
    loadable: false, tags: ['warmup', 'knee_friendly', 'rehab_friendly'], space: 'medium' }),

  // ---------------------------------------------------------------- מכונות שהיו חסרות כיסוי
  ex({ id: 'leg_extension', name: 'פשיטת ברכיים במכונה', nameEn: 'Leg Extension',
    type: 'isolation', pattern: 'squat', primary: ['quads'],
    eq: [['leg_extension']], skill: 1, fatigue: 'low', repMin: 10, repMax: 20,
    stress: { knee: 2 }, tags: ['beginner_friendly'] }),
  ex({ id: 'machine_pullover', name: 'פולאובר במכונה', nameEn: 'Machine Pullover',
    type: 'isolation', pattern: 'vertical_pull', primary: ['back_lats'],
    eq: [['pullover_machine']], skill: 1, fatigue: 'low', repMin: 10, repMax: 20,
    stress: { shoulder: 1 }, flags: F('overhead') }),
  ex({ id: 'ab_machine_crunch', name: 'כפיפת בטן במכונה', nameEn: 'Machine Crunch',
    type: 'isolation', pattern: 'core_flexion', primary: ['core_anterior'],
    eq: [['ab_machine']], skill: 1, fatigue: 'low', repMin: 10, repMax: 20,
    stress: { lumbar: 2 }, flags: F('spinal_flexion'), tags: ['beginner_friendly'] }),
  ex({ id: 'elliptical_intervals', name: 'אליפטיקל', nameEn: 'Elliptical Intervals',
    type: 'conditioning', pattern: 'conditioning', primary: ['quads', 'glutes'],
    eq: [['elliptical']], skill: 1, fatigue: 'moderate', repMin: 300, repMax: 1800, loadable: false,
    stress: { cardio: 2 }, tags: ['low_impact', 'joint_friendly'] }),
  ex({ id: 'sandbag_carry', name: 'נשיאת שק חול', nameEn: 'Sandbag Carry',
    type: 'carry', pattern: 'carry', primary: ['core_anterior', 'back_upper'], secondary: ['glutes'],
    eq: [['sandbag']], skill: 2, fatigue: 'high', repMin: 20, repMax: 60,
    stress: { lumbar: 2 }, flags: F('grip_intensive'), space: 'large', tags: ['functional'] }),
  ex({ id: 'stability_ball_curl', name: 'כפיפת ברכיים בכדור פיזיו', nameEn: 'Stability Ball Leg Curl',
    pattern: 'hinge', primary: ['hamstrings'], secondary: ['glutes', 'core_anterior'],
    eq: [['stability_ball']], skill: 3, fatigue: 'moderate', repMin: 8, repMax: 15, loadable: false,
    stress: { knee: 1 }, flags: F('lying_supine', 'floor_transition', 'unstable') }),
  ex({ id: 'good_morning', name: 'גוד מורנינג', nameEn: 'Good Morning',
    pattern: 'hinge', primary: ['hamstrings', 'core_posterior'], secondary: ['glutes'],
    eq: [['barbell'], ['resistance_band']], skill: 4, fatigue: 'high', repMin: 6, repMax: 15,
    stress: { lumbar: 3, hip: 2 }, flags: F('spinal_loading') }),
  ex({ id: 'shrug', name: 'משיכת כתפיים', nameEn: 'Shrug',
    type: 'isolation', pattern: 'horizontal_pull', primary: ['back_upper'],
    eq: [['dumbbell'], ['barbell'], ['trap_bar']], skill: 1, fatigue: 'low', repMin: 8, repMax: 20,
    stress: { neck: 1 }, flags: F('grip_intensive') }),
  ex({ id: 'front_raise', name: 'הרמות קדמיות', nameEn: 'Front Raise',
    type: 'isolation', pattern: 'shoulder_isolation', primary: ['delts_front'],
    eq: [['dumbbell'], ['cable_crossover'], ['resistance_band']], skill: 1, fatigue: 'low',
    repMin: 10, repMax: 20, stress: { shoulder: 2 } }),
  ex({ id: 'russian_twist', name: 'סיבובים רוסיים', nameEn: 'Russian Twist',
    type: 'isolation', pattern: 'core_antirotation', primary: ['core_lateral'],
    eq: [['medicine_ball'], ['dumbbell'], ['bodyweight']], plane: 'transverse', skill: 2, fatigue: 'low',
    repMin: 10, repMax: 24, loadable: false, stress: { lumbar: 2 },
    flags: F('spinal_rotation', 'spinal_flexion', 'floor_transition') }),
  ex({ id: 'mountain_climber', name: 'מטפסי הרים', nameEn: 'Mountain Climber',
    type: 'conditioning', pattern: 'conditioning', primary: ['core_anterior'], secondary: ['delts_front'],
    eq: [['bodyweight'], ['mat']], skill: 2, fatigue: 'high', repMin: 20, repMax: 60, loadable: false,
    stress: { wrist: 2, cardio: 3, shoulder: 1 }, flags: F('wrist_extension_load', 'floor_transition') }),
  ex({ id: 'bear_crawl', name: 'הליכת דוב', nameEn: 'Bear Crawl',
    type: 'conditioning', pattern: 'conditioning', primary: ['core_anterior'], secondary: ['delts_front', 'quads'],
    eq: [['bodyweight']], skill: 3, fatigue: 'high', repMin: 15, repMax: 45, loadable: false,
    stress: { wrist: 2, shoulder: 1, cardio: 2 }, flags: F('wrist_extension_load', 'floor_transition'),
    space: 'large' }),
  ex({ id: 'foam_roll_thoracic', name: 'גלגול חזי בגליל', nameEn: 'Thoracic Foam Rolling',
    type: 'mobility', pattern: 'mobility', primary: ['core_posterior'],
    eq: [['foam_roller']], skill: 1, fatigue: 'low', repMin: 30, repMax: 90, loadable: false,
    flags: F('lying_supine', 'floor_transition'), tags: ['warmup', 'posture'] }),

  // ---------------------------------------------------------------- כיסא, תמיכה ונגישות
  ex({ id: 'sit_to_stand', name: 'קימה מכיסא', nameEn: 'Sit-to-Stand',
    pattern: 'squat', primary: ['quads', 'glutes'],
    // תרגיל משקל גוף: הכיסא הוא היעד, לא ההתנגדות. סימונו כ"ניתן להעמסה"
    // גרם להצגתו בלי משקל עבודה, כאילו חסר נתון
    eq: [['chair'], ['bench_flat'], ['plyo_box']], skill: 1, fatigue: 'low', repMin: 5, repMax: 20, loadable: false,
    stress: { knee: 1 }, tags: ['regression', 'beginner_friendly', 'knee_friendly', 'functional', 'active_aging'],
    cues: ['אף כף רגל מתחת לברך', 'לדחוף דרך העקבים', 'לשבת בשליטה, לא ליפול'] }),
  ex({ id: 'power_sit_to_stand', name: 'קימה מהירה מכיסא', nameEn: 'Power Sit-to-Stand',
    pattern: 'squat', primary: ['quads', 'glutes'],
    eq: [['chair'], ['bench_flat']], skill: 2, fatigue: 'moderate', repMin: 5, repMax: 10, loadable: false,
    stress: { knee: 1 }, flags: F('ballistic'), tags: ['power', 'active_aging', 'low_impact'],
    cues: ['עלייה מהירה, ירידה איטית ומבוקרת'] }),
  ex({ id: 'wall_pushup', name: 'שכיבות סמיכה לקיר', nameEn: 'Wall Push-up',
    pattern: 'horizontal_push', primary: ['chest'], secondary: ['triceps'],
    eq: [['wall'], ['bodyweight']], skill: 1, fatigue: 'low', repMin: 8, repMax: 25, loadable: false,
    stress: { shoulder: 1, wrist: 1 }, tags: ['regression', 'beginner_friendly', 'active_aging'] }),
  ex({ id: 'seated_band_row', name: 'חתירה בגומייה בישיבה', nameEn: 'Seated Band Row',
    pattern: 'horizontal_pull', primary: ['back_upper'], secondary: ['biceps'],
    eq: [['resistance_band', 'chair'], ['resistance_band']], skill: 1, fatigue: 'low',
    repMin: 10, repMax: 25, loadable: false,
    tags: ['regression', 'beginner_friendly', 'rehab_friendly', 'active_aging', 'posture'] }),
  ex({ id: 'seated_db_press', name: 'לחיצת כתפיים בישיבה על כיסא', nameEn: 'Chair Shoulder Press',
    pattern: 'vertical_push', primary: ['delts_front'], secondary: ['triceps'],
    eq: [['dumbbell', 'chair'], ['resistance_band', 'chair']], skill: 1, fatigue: 'low',
    repMin: 8, repMax: 18, stress: { shoulder: 2 }, flags: F('overhead'),
    tags: ['beginner_friendly', 'active_aging'] }),
  ex({ id: 'supported_single_leg_stance', name: 'עמידה על רגל אחת בתמיכה', nameEn: 'Supported Single-leg Stance',
    type: 'isolation', pattern: 'core_antilateralflexion', primary: ['core_lateral'], secondary: ['abductors'],
    eq: [['stable_support'], ['chair'], ['wall'], ['parallel_bars']], unilateral: true,
    skill: 1, fatigue: 'low', repMin: 10, repMax: 45, loadable: false,
    tags: ['isometric', 'active_aging', 'rehab_friendly', 'balance_training'],
    cues: ['יד קלה על התמיכה בלבד', 'מבט קדימה', 'להתקדם להורדת אצבע אחת'] }),
  ex({ id: 'tandem_walk', name: 'הליכת עקב-אצבע', nameEn: 'Tandem Walk',
    type: 'isolation', pattern: 'core_antilateralflexion', primary: ['core_lateral'],
    eq: [['stable_support'], ['bodyweight'], ['parallel_bars']], skill: 2, fatigue: 'low',
    repMin: 10, repMax: 30, loadable: false, flags: F('balance'), space: 'large',
    tags: ['active_aging', 'balance_training', 'rehab_friendly'] }),
  ex({ id: 'supported_calf_raise', name: 'הרמת עקבים בתמיכה', nameEn: 'Supported Calf Raise',
    type: 'isolation', pattern: 'calf', primary: ['calves'],
    eq: [['stable_support'], ['chair'], ['wall']], skill: 1, fatigue: 'low', repMin: 10, repMax: 25,
    stress: { ankle: 1 }, tags: ['regression', 'beginner_friendly', 'active_aging', 'rehab_friendly'] }),
  ex({ id: 'hinge_to_chair', name: 'הינג׳ אל הכיסא', nameEn: 'Hip Hinge to Chair',
    pattern: 'hinge', primary: ['glutes', 'hamstrings'],
    eq: [['chair'], ['bench_flat']], skill: 1, fatigue: 'low', repMin: 8, repMax: 15, loadable: false,
    stress: { lumbar: 1 }, tags: ['regression', 'beginner_friendly', 'back_friendly', 'active_aging'],
    cues: ['לדחוף אגן אחורה אל הכיסא', 'גב ניטרלי לאורך כל התנועה'] }),
  ex({ id: 'arm_ergometer', name: 'ארגומטר ידיים', nameEn: 'Arm Ergometer',
    type: 'conditioning', pattern: 'conditioning', primary: ['delts_front', 'back_upper'],
    eq: [['arm_ergometer']], skill: 1, fatigue: 'moderate', repMin: 180, repMax: 1200, loadable: false,
    stress: { cardio: 2, shoulder: 1 },
    tags: ['low_impact', 'joint_friendly', 'upper_body_only'] }),
  ex({ id: 'recumbent_bike', name: 'אופני שכיבה', nameEn: 'Recumbent Bike',
    type: 'conditioning', pattern: 'conditioning', primary: ['quads'],
    eq: [['recumbent_bike']], skill: 1, fatigue: 'low', repMin: 300, repMax: 2400, loadable: false,
    stress: { cardio: 2 }, tags: ['low_impact', 'joint_friendly', 'back_friendly', 'active_aging'] }),
  ex({ id: 'heel_drops', name: 'נחיתות עקב לחיזוק עצם', nameEn: 'Heel Drops',
    type: 'isolation', pattern: 'calf', primary: ['calves'],
    eq: [['stable_support'], ['bodyweight']], skill: 1, fatigue: 'low', repMin: 8, repMax: 20,
    loadable: false, stress: { ankle: 2 }, flags: F('impact'), noisy: true,
    tags: ['bone_loading'], cues: ['עלייה על קצות האצבעות והורדה נחרצת של העקב'] }),

  // ---------------------------------------------------------------- פילאטיס ומזרן
  ex({ id: 'reformer_footwork', name: 'ריפורמר — פוטוורק', nameEn: 'Reformer Footwork',
    pattern: 'squat', primary: ['quads', 'glutes'], secondary: ['calves'],
    eq: [['reformer']], skill: 2, fatigue: 'moderate', repMin: 8, repMax: 20,
    stress: { knee: 1 }, flags: F('lying_supine'),
    tags: ['pilates', 'joint_friendly', 'back_friendly'] }),
  ex({ id: 'reformer_footstraps', name: 'ריפורמר — רגליים ברצועות', nameEn: 'Reformer Feet in Straps',
    pattern: 'hinge', primary: ['glutes', 'hamstrings'], secondary: ['core_anterior'],
    eq: [['reformer']], skill: 3, fatigue: 'moderate', repMin: 8, repMax: 15,
    flags: F('lying_supine'), tags: ['pilates', 'rehab_friendly'] }),
  ex({ id: 'reformer_row', name: 'ריפורמר — חתירה', nameEn: 'Reformer Row',
    pattern: 'horizontal_pull', primary: ['back_upper'], secondary: ['biceps', 'core_anterior'],
    eq: [['reformer']], skill: 3, fatigue: 'moderate', repMin: 8, repMax: 15,
    tags: ['pilates', 'posture'] }),
  ex({ id: 'reformer_long_stretch', name: 'ריפורמר — לונג סטרץ׳', nameEn: 'Reformer Long Stretch',
    pattern: 'core_antiextension', primary: ['core_anterior'], secondary: ['delts_front', 'chest'],
    eq: [['reformer']], skill: 4, fatigue: 'moderate', repMin: 5, repMax: 12, loadable: false,
    stress: { shoulder: 1, wrist: 1 }, tags: ['pilates'] }),
  ex({ id: 'reformer_side_split', name: 'ריפורמר — סייד ספליט', nameEn: 'Reformer Side Split',
    type: 'isolation', pattern: 'hip_abduction', primary: ['adductors', 'abductors'],
    eq: [['reformer']], plane: 'frontal', skill: 4, fatigue: 'moderate', repMin: 6, repMax: 12,
    stress: { hip: 1 }, flags: F('hip_adduction_load'), tags: ['pilates'] }),
  ex({ id: 'pilates_hundred', name: 'פילאטיס — המאה', nameEn: 'Pilates Hundred',
    type: 'isolation', pattern: 'core_flexion', primary: ['core_anterior'],
    eq: [['pilates_mat'], ['mat']], skill: 3, fatigue: 'low', repMin: 20, repMax: 100, loadable: false,
    stress: { lumbar: 2, neck: 2 }, flags: F('spinal_flexion', 'lying_supine', 'floor_transition'),
    tags: ['pilates'] }),
  ex({ id: 'pilates_swan', name: 'פילאטיס — ברבור', nameEn: 'Pilates Swan',
    type: 'isolation', pattern: 'core_antirotation', primary: ['core_posterior'], secondary: ['back_upper'],
    eq: [['pilates_mat'], ['mat']], skill: 2, fatigue: 'low', repMin: 5, repMax: 12, loadable: false,
    stress: { lumbar: 1 }, flags: F('lying_prone', 'floor_transition'),
    tags: ['pilates', 'posture'] }),
  ex({ id: 'pilates_side_kick', name: 'פילאטיס — בעיטות צד', nameEn: 'Pilates Side Kick Series',
    type: 'isolation', pattern: 'hip_abduction', primary: ['abductors', 'glutes'],
    eq: [['pilates_mat'], ['mat']], plane: 'frontal', unilateral: true, skill: 2, fatigue: 'low',
    repMin: 8, repMax: 20, loadable: false, flags: F('floor_transition'),
    tags: ['pilates', 'rehab_friendly'] }),
  ex({ id: 'pilates_ring_squeeze', name: 'לחיצת טבעת בין הברכיים', nameEn: 'Pilates Ring Inner Thigh Squeeze',
    type: 'isolation', pattern: 'hip_abduction', primary: ['adductors'],
    eq: [['pilates_ring'], ['small_ball']], plane: 'frontal', skill: 1, fatigue: 'low',
    repMin: 10, repMax: 25, loadable: false, flags: F('hip_adduction_load'),
    tags: ['pilates', 'rehab_friendly'] }),
  ex({ id: 'pilates_chair_step', name: 'כיסא פילאטיס — סטפ אפ', nameEn: 'Pilates Chair Step-up',
    pattern: 'lunge', primary: ['quads', 'glutes'],
    eq: [['pilates_chair']], unilateral: true, skill: 3, fatigue: 'moderate', repMin: 6, repMax: 15,
    stress: { knee: 1 }, flags: F('balance'), tags: ['pilates'] }),

  // ---------------------------------------------------------------- אגרוף וקרב
  ex({ id: 'heavy_bag_rounds', name: 'סבבים בשק אגרוף', nameEn: 'Heavy Bag Rounds',
    type: 'conditioning', pattern: 'conditioning', primary: ['delts_front', 'core_lateral'],
    secondary: ['back_upper', 'calves'],
    eq: [['heavy_bag']], skill: 3, fatigue: 'high', repMin: 60, repMax: 180, loadable: false,
    stress: { cardio: 3, shoulder: 1, wrist: 1 }, flags: F('ballistic', 'spinal_rotation'),
    space: 'medium', noisy: true, tags: ['conditioning', 'stress_relief'] }),
  ex({ id: 'pad_work', name: 'עבודת מיטים עם מאמן', nameEn: 'Pad Work',
    type: 'conditioning', pattern: 'conditioning', primary: ['delts_front', 'core_lateral'],
    eq: [['boxing_pads']], skill: 3, fatigue: 'high', repMin: 60, repMax: 180, loadable: false,
    stress: { cardio: 3, shoulder: 1 }, flags: F('ballistic', 'spinal_rotation'),
    space: 'medium', tags: ['conditioning', 'stress_relief'] }),
  ex({ id: 'shadow_boxing', name: 'צל-אגרוף', nameEn: 'Shadow Boxing',
    type: 'conditioning', pattern: 'conditioning', primary: ['delts_front'], secondary: ['core_lateral'],
    eq: [['bodyweight']], skill: 2, fatigue: 'moderate', repMin: 60, repMax: 180, loadable: false,
    stress: { cardio: 2, shoulder: 1 }, space: 'medium',
    tags: ['conditioning', 'stress_relief', 'no_equipment', 'low_impact'] }),

  // ---------------------------------------------------------------- ניידות ורגיעה
  ex({ id: 'nasal_breathing_cooldown', name: 'נשימות סרעפתיות לסיום', nameEn: 'Diaphragmatic Breathing Cool-down',
    type: 'mobility', pattern: 'mobility', primary: ['core_anterior'],
    eq: [['mat'], ['bodyweight'], ['chair']], skill: 1, fatigue: 'low', repMin: 60, repMax: 180,
    loadable: false, tags: ['cooldown', 'stress_relief', 'rehab_friendly'],
    cues: ['שאיפה 4 שניות דרך האף, נשיפה ארוכה 6-8 שניות'] }),
  ex({ id: 'world_greatest_stretch', name: 'מתיחת הקומבו הגדולה', nameEn: "World's Greatest Stretch",
    type: 'mobility', pattern: 'mobility', primary: ['hip'], secondary: ['core_posterior'],
    eq: [['mat'], ['bodyweight']], plane: 'transverse', unilateral: true, skill: 2, fatigue: 'low',
    repMin: 4, repMax: 10, loadable: false, flags: F('floor_transition', 'spinal_rotation'),
    space: 'medium', tags: ['warmup', 'mobility'] }),
  ex({ id: 'hamstring_stretch_supine', name: 'מתיחת אחורי ירך בשכיבה', nameEn: 'Supine Hamstring Stretch',
    type: 'mobility', pattern: 'mobility', primary: ['hamstrings'],
    eq: [['mat'], ['resistance_band'], ['bodyweight']], skill: 1, fatigue: 'low', repMin: 20, repMax: 60,
    loadable: false, flags: F('lying_supine', 'floor_transition'), tags: ['cooldown', 'mobility'] }),
  ex({ id: 'seated_thoracic_opener', name: 'פתיחת חזה בישיבה', nameEn: 'Seated Chest Opener',
    type: 'mobility', pattern: 'mobility', primary: ['chest'], secondary: ['back_upper'],
    eq: [['chair'], ['bodyweight'], ['resistance_band']], skill: 1, fatigue: 'low', repMin: 20, repMax: 45,
    loadable: false, tags: ['warmup', 'cooldown', 'posture', 'active_aging'] }),
  ex({ id: 'general_cardio_warmup', name: 'חימום אירובי כללי', nameEn: 'General Cardio Warm-up',
    type: 'mobility', pattern: 'mobility', primary: ['quads'],
    eq: [['treadmill'], ['bike'], ['rower'], ['elliptical'], ['recumbent_bike'], ['bodyweight']],
    skill: 1, fatigue: 'low', repMin: 180, repMax: 480, loadable: false,
    stress: { cardio: 1 }, tags: ['warmup'],
    cues: ['3-5 דקות בעצימות קלה עד להזעה קלה'] }),
  ex({ id: 'decline_press', name: 'לחיצת חזה בשיפוע שלילי', nameEn: 'Decline Press',
    pattern: 'horizontal_push', primary: ['chest'], secondary: ['triceps'],
    eq: [['bench_decline', 'dumbbell'], ['bench_decline', 'barbell']], skill: 2, fatigue: 'high',
    repMin: 6, repMax: 15, stress: { shoulder: 1, elbow: 1 },
    flags: F('lying_supine', 'head_below_heart'), tags: ['shoulder_friendly'] }),
  ex({ id: 'bosu_balance_squat', name: 'סקוואט על בוסו', nameEn: 'Bosu Balance Squat',
    pattern: 'squat', primary: ['quads', 'glutes'], secondary: ['core_lateral'],
    eq: [['bosu']], skill: 4, fatigue: 'moderate', repMin: 6, repMax: 15, loadable: false,
    stress: { knee: 1, ankle: 1 }, flags: F('unstable', 'balance'), tags: ['balance_training'] }),
  ex({ id: 'cadillac_leg_springs', name: 'קדילק — קפיצי רגליים', nameEn: 'Cadillac Leg Springs',
    pattern: 'hinge', primary: ['glutes', 'hamstrings'], secondary: ['core_anterior'],
    eq: [['cadillac']], skill: 3, fatigue: 'moderate', repMin: 8, repMax: 15,
    flags: F('lying_supine'), tags: ['pilates', 'rehab_friendly', 'back_friendly'] }),
  ex({ id: 'barrel_thoracic_extension', name: 'חבית — פתיחת חזה', nameEn: 'Barrel Thoracic Extension',
    type: 'mobility', pattern: 'mobility', primary: ['core_posterior'], secondary: ['chest'],
    eq: [['pilates_barrel']], skill: 2, fatigue: 'low', repMin: 20, repMax: 60, loadable: false,
    flags: F('lying_supine'), tags: ['pilates', 'posture', 'cooldown'] }),
  ex({ id: 'speed_bag_rounds', name: 'כדור מהירות', nameEn: 'Speed Bag Rounds',
    type: 'conditioning', pattern: 'conditioning', primary: ['delts_front'], secondary: ['forearms'],
    eq: [['speed_bag']], skill: 4, fatigue: 'moderate', repMin: 45, repMax: 180, loadable: false,
    stress: { cardio: 2, shoulder: 2 }, flags: F('overhead'), noisy: true, tags: ['conditioning'] }),
  ex({ id: 'neck_isometric', name: 'איזומטרי צוואר', nameEn: 'Neck Isometric Hold',
    type: 'isolation', pattern: 'core_antirotation', primary: ['neck'],
    eq: [['bodyweight'], ['resistance_band']], skill: 1, fatigue: 'low', repMin: 10, repMax: 30,
    loadable: false, stress: { neck: 1 }, tags: ['isometric', 'rehab_friendly', 'posture'],
    cues: ['לחץ קל של כף היד כנגד הראש, ללא תנועה, נשימה רציפה'] }),
];

/**
 * הופך תרגיל שהמאמן כתב בעצמו לאובייקט תרגיל מלא שהמנוע יודע לעבוד איתו.
 * שדות שהמאמן לא מילא מקבלים ברירות מחדל שמרניות: התרגיל נחשב עזר,
 * בעומס נמוך ובלי דגלי סיכון — כדי שהוא לעולם לא ייכנס במקום תרגיל עיקרי
 * רק משום שאין עליו מידע.
 */
export function customToExercise(c) {
  const reps = String(c.reps ?? '10');
  const nums = reps.match(/\d+/g)?.map(Number) || [10];
  return ex({
    id: c.id,
    name: c.name,
    nameEn: c.name,
    description: c.description || '',
    custom: true,
    type: c.pattern ? 'compound' : 'isolation',
    pattern: c.pattern || 'core_antiextension',
    primary: c.primaryMuscle ? [c.primaryMuscle] : ['core_anterior'],
    secondary: [],
    eq: c.equipment && c.equipment.length ? [c.equipment] : [['bodyweight']],
    skill: 1,
    fatigue: 'moderate',
    repMin: Math.min(...nums),
    repMax: Math.max(...nums),
    loadable: !!c.load,
    tags: ['custom'],
    cues: c.notes ? [c.notes] : [],
    setupSeconds: 30,
  });
}

/** אינדקס לפי מזהה. */
export const BY_ID = Object.fromEntries(EXERCISES.map((e) => [e.id, e]));

/** @param {string} id */
export function getExercise(id) {
  const e = BY_ID[id];
  if (!e) throw new Error(`תרגיל לא מוכר: ${id}`);
  return e;
}
